### ISSUE TITLE
[FEATURE] 프로필 편집 링크 편집

### ISSUE THREAD

**Issue by wngus4296** [Nexters/Boolti-iOS#329]
## 🎧 About
<img width="694" alt="image" src="https://github.com/user-attachments/assets/448e9387-7557-4837-9fa2-5d9eac7dc94e">

## 🎶 Branch Name
feature/#?-

## 🎹 To do
- [ ]

**Comment by longlivedrgn** [comment]
https://github.com/Nexters/Boolti-iOS/pull/340
- 해당 이슈 해결
